/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This hash is used to attest that the beneficial owner information provided to Stripe is both current and correct.
*/
export class AccountCompanyOwnershipDeclaration {
    /**
    * The Unix timestamp marking when the beneficial owner attestation was made.
    */
    'date': number | null;
    /**
    * The IP address from which the beneficial owner attestation was made.
    */
    'ip': string | null;
    /**
    * The user-agent string from the browser where the beneficial owner attestation was made.
    */
    'userAgent': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "number"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountCompanyOwnershipDeclaration.attributeTypeMap;
    }
}

