/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountTosAcceptance {
    /**
    * The Unix timestamp marking when the account representative accepted their service agreement
    */
    'date'?: number | null;
    /**
    * The IP address from which the account representative accepted their service agreement
    */
    'ip'?: string | null;
    /**
    * The user\'s service agreement type
    */
    'serviceAgreement'?: string;
    /**
    * The user agent of the browser from which the account representative accepted their service agreement
    */
    'userAgent'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "number"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "serviceAgreement",
            "baseName": "service_agreement",
            "type": "string"
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountTosAcceptance.attributeTypeMap;
    }
}

