/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthorizationMerchantData {
    /**
    * A categorization of the seller\'s type of business. See our [merchant categories guide](https://stripe.com/docs/issuing/merchant-categories) for a list of possible values.
    */
    'category': string;
    /**
    * The merchant category code for the seller\'s business
    */
    'categoryCode': string;
    /**
    * City where the seller is located
    */
    'city': string | null;
    /**
    * Country where the seller is located
    */
    'country': string | null;
    /**
    * Name of the seller
    */
    'name': string | null;
    /**
    * Identifier assigned to the seller by the card network. Different card networks may assign different network_id fields to the same merchant.
    */
    'networkId': string;
    /**
    * Postal code where the seller is located
    */
    'postalCode': string | null;
    /**
    * State where the seller is located
    */
    'state': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "categoryCode",
            "baseName": "category_code",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "networkId",
            "baseName": "network_id",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthorizationMerchantData.attributeTypeMap;
    }
}

