/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BalanceTransactionType {
    ADJUSTMENT = <any> 'adjustment',
    ADVANCE = <any> 'advance',
    ADVANCE_FUNDING = <any> 'advance_funding',
    ANTICIPATION_REPAYMENT = <any> 'anticipation_repayment',
    APPLICATION_FEE = <any> 'application_fee',
    APPLICATION_FEE_REFUND = <any> 'application_fee_refund',
    CHARGE = <any> 'charge',
    CONNECT_COLLECTION_TRANSFER = <any> 'connect_collection_transfer',
    CONTRIBUTION = <any> 'contribution',
    ISSUING_AUTHORIZATION_HOLD = <any> 'issuing_authorization_hold',
    ISSUING_AUTHORIZATION_RELEASE = <any> 'issuing_authorization_release',
    ISSUING_DISPUTE = <any> 'issuing_dispute',
    ISSUING_TRANSACTION = <any> 'issuing_transaction',
    PAYMENT = <any> 'payment',
    PAYMENT_FAILURE_REFUND = <any> 'payment_failure_refund',
    PAYMENT_REFUND = <any> 'payment_refund',
    PAYOUT = <any> 'payout',
    PAYOUT_CANCEL = <any> 'payout_cancel',
    PAYOUT_FAILURE = <any> 'payout_failure',
    REFUND = <any> 'refund',
    REFUND_FAILURE = <any> 'refund_failure',
    RESERVE_TRANSACTION = <any> 'reserve_transaction',
    RESERVED_FUNDS = <any> 'reserved_funds',
    STRIPE_FEE = <any> 'stripe_fee',
    STRIPE_FX_FEE = <any> 'stripe_fx_fee',
    TAX_FEE = <any> 'tax_fee',
    TOPUP = <any> 'topup',
    TOPUP_REVERSAL = <any> 'topup_reversal',
    TRANSFER = <any> 'transfer',
    TRANSFER_CANCEL = <any> 'transfer_cancel',
    TRANSFER_FAILURE = <any> 'transfer_failure',
    TRANSFER_REFUND = <any> 'transfer_refund'
}
