/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CardholderCompany {
    /**
    * Whether the company\'s business ID number was provided.
    */
    'taxIdProvided': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taxIdProvided",
            "baseName": "tax_id_provided",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CardholderCompany.attributeTypeMap;
    }
}

