/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum CardNetwork {
    AMEX = <any> 'amex',
    CARTES_BANCAIRES = <any> 'cartes_bancaires',
    DINERS = <any> 'diners',
    DISCOVER = <any> 'discover',
    INTERAC = <any> 'interac',
    JCB = <any> 'jcb',
    MASTERCARD = <any> 'mastercard',
    UNIONPAY = <any> 'unionpay',
    UNKNOWN = <any> 'unknown',
    VISA = <any> 'visa'
}
