/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargeTransferDataDestination } from './chargeTransferDataDestination';

export class ChargeTransferData {
    /**
    * The amount transferred to the destination account, if specified. By default, the entire charge amount is transferred to the destination account.
    */
    'amount': number | null;
    'destination': ChargeTransferDataDestination;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "ChargeTransferDataDestination"
        }    ];

    static getAttributeTypeMap() {
        return ChargeTransferData.attributeTypeMap;
    }
}

