/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodDetailsAchCreditTransfer } from './paymentMethodDetailsAchCreditTransfer';
import { PaymentMethodDetailsAchDebit } from './paymentMethodDetailsAchDebit';
import { PaymentMethodDetailsAfterpayClearpay } from './paymentMethodDetailsAfterpayClearpay';
import { PaymentMethodDetailsAlipay } from './paymentMethodDetailsAlipay';
import { PaymentMethodDetailsBancontact } from './paymentMethodDetailsBancontact';
import { PaymentMethodDetailsBlik } from './paymentMethodDetailsBlik';
import { PaymentMethodDetailsCardPresent } from './paymentMethodDetailsCardPresent';
import { PaymentMethodDetailsEps } from './paymentMethodDetailsEps';
import { PaymentMethodDetailsFpx } from './paymentMethodDetailsFpx';
import { PaymentMethodDetailsGiropay } from './paymentMethodDetailsGiropay';
import { PaymentMethodDetailsGrabpay } from './paymentMethodDetailsGrabpay';
import { PaymentMethodDetailsIdeal } from './paymentMethodDetailsIdeal';
import { PaymentMethodDetailsInteracPresent } from './paymentMethodDetailsInteracPresent';
import { PaymentMethodDetailsKonbini } from './paymentMethodDetailsKonbini';
import { PaymentMethodDetailsMultibanco } from './paymentMethodDetailsMultibanco';
import { PaymentMethodDetailsOxxo } from './paymentMethodDetailsOxxo';
import { PaymentMethodDetailsP24 } from './paymentMethodDetailsP24';
import { PaymentMethodDetailsPaynow } from './paymentMethodDetailsPaynow';
import { PaymentMethodDetailsPix } from './paymentMethodDetailsPix';
import { PaymentMethodDetailsPromptpay } from './paymentMethodDetailsPromptpay';
import { PaymentMethodDetailsSepaCreditTransfer } from './paymentMethodDetailsSepaCreditTransfer';
import { PaymentMethodDetailsSepaDebit } from './paymentMethodDetailsSepaDebit';
import { PaymentMethodDetailsSofort } from './paymentMethodDetailsSofort';
import { PaymentMethodDetailsWechatPay } from './paymentMethodDetailsWechatPay';

export class ChargePaymentMethodDetails {
    'achCreditTransfer'?: PaymentMethodDetailsAchCreditTransfer;
    'achDebit'?: PaymentMethodDetailsAchDebit;
    'acssDebit'?: object;
    'affirm'?: object;
    'afterpayClearpay'?: PaymentMethodDetailsAfterpayClearpay;
    'alipay'?: PaymentMethodDetailsAlipay;
    'auBecsDebit'?: object;
    'bacsDebit'?: object;
    'bancontact'?: PaymentMethodDetailsBancontact;
    'blik'?: PaymentMethodDetailsBlik;
    'boleto'?: object;
    'card'?: object;
    'cardPresent'?: PaymentMethodDetailsCardPresent;
    'customerBalance'?: object;
    'eps'?: PaymentMethodDetailsEps;
    'fpx'?: PaymentMethodDetailsFpx;
    'giropay'?: PaymentMethodDetailsGiropay;
    'grabpay'?: PaymentMethodDetailsGrabpay;
    'ideal'?: PaymentMethodDetailsIdeal;
    'interacPresent'?: PaymentMethodDetailsInteracPresent;
    'klarna'?: object;
    'konbini'?: PaymentMethodDetailsKonbini;
    'link'?: object;
    'multibanco'?: PaymentMethodDetailsMultibanco;
    'oxxo'?: PaymentMethodDetailsOxxo;
    'p24'?: PaymentMethodDetailsP24;
    'paynow'?: PaymentMethodDetailsPaynow;
    'pix'?: PaymentMethodDetailsPix;
    'promptpay'?: PaymentMethodDetailsPromptpay;
    'sepaCreditTransfer'?: PaymentMethodDetailsSepaCreditTransfer;
    'sepaDebit'?: PaymentMethodDetailsSepaDebit;
    'sofort'?: PaymentMethodDetailsSofort;
    'stripeAccount'?: object;
    /**
    * The type of transaction-specific details of the payment method used in the payment, one of `ach_credit_transfer`, `ach_debit`, `acss_debit`, `alipay`, `au_becs_debit`, `bancontact`, `card`, `card_present`, `eps`, `giropay`, `ideal`, `klarna`, `multibanco`, `p24`, `sepa_debit`, `sofort`, `stripe_account`, or `wechat`. An additional hash is included on `payment_method_details` with a name matching this value. It contains information specific to the payment method.
    */
    'type': string;
    'usBankAccount'?: object;
    'wechat'?: object;
    'wechatPay'?: PaymentMethodDetailsWechatPay;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "achCreditTransfer",
            "baseName": "ach_credit_transfer",
            "type": "PaymentMethodDetailsAchCreditTransfer"
        },
        {
            "name": "achDebit",
            "baseName": "ach_debit",
            "type": "PaymentMethodDetailsAchDebit"
        },
        {
            "name": "acssDebit",
            "baseName": "acss_debit",
            "type": "object"
        },
        {
            "name": "affirm",
            "baseName": "affirm",
            "type": "object"
        },
        {
            "name": "afterpayClearpay",
            "baseName": "afterpay_clearpay",
            "type": "PaymentMethodDetailsAfterpayClearpay"
        },
        {
            "name": "alipay",
            "baseName": "alipay",
            "type": "PaymentMethodDetailsAlipay"
        },
        {
            "name": "auBecsDebit",
            "baseName": "au_becs_debit",
            "type": "object"
        },
        {
            "name": "bacsDebit",
            "baseName": "bacs_debit",
            "type": "object"
        },
        {
            "name": "bancontact",
            "baseName": "bancontact",
            "type": "PaymentMethodDetailsBancontact"
        },
        {
            "name": "blik",
            "baseName": "blik",
            "type": "PaymentMethodDetailsBlik"
        },
        {
            "name": "boleto",
            "baseName": "boleto",
            "type": "object"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "object"
        },
        {
            "name": "cardPresent",
            "baseName": "card_present",
            "type": "PaymentMethodDetailsCardPresent"
        },
        {
            "name": "customerBalance",
            "baseName": "customer_balance",
            "type": "object"
        },
        {
            "name": "eps",
            "baseName": "eps",
            "type": "PaymentMethodDetailsEps"
        },
        {
            "name": "fpx",
            "baseName": "fpx",
            "type": "PaymentMethodDetailsFpx"
        },
        {
            "name": "giropay",
            "baseName": "giropay",
            "type": "PaymentMethodDetailsGiropay"
        },
        {
            "name": "grabpay",
            "baseName": "grabpay",
            "type": "PaymentMethodDetailsGrabpay"
        },
        {
            "name": "ideal",
            "baseName": "ideal",
            "type": "PaymentMethodDetailsIdeal"
        },
        {
            "name": "interacPresent",
            "baseName": "interac_present",
            "type": "PaymentMethodDetailsInteracPresent"
        },
        {
            "name": "klarna",
            "baseName": "klarna",
            "type": "object"
        },
        {
            "name": "konbini",
            "baseName": "konbini",
            "type": "PaymentMethodDetailsKonbini"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "object"
        },
        {
            "name": "multibanco",
            "baseName": "multibanco",
            "type": "PaymentMethodDetailsMultibanco"
        },
        {
            "name": "oxxo",
            "baseName": "oxxo",
            "type": "PaymentMethodDetailsOxxo"
        },
        {
            "name": "p24",
            "baseName": "p24",
            "type": "PaymentMethodDetailsP24"
        },
        {
            "name": "paynow",
            "baseName": "paynow",
            "type": "PaymentMethodDetailsPaynow"
        },
        {
            "name": "pix",
            "baseName": "pix",
            "type": "PaymentMethodDetailsPix"
        },
        {
            "name": "promptpay",
            "baseName": "promptpay",
            "type": "PaymentMethodDetailsPromptpay"
        },
        {
            "name": "sepaCreditTransfer",
            "baseName": "sepa_credit_transfer",
            "type": "PaymentMethodDetailsSepaCreditTransfer"
        },
        {
            "name": "sepaDebit",
            "baseName": "sepa_debit",
            "type": "PaymentMethodDetailsSepaDebit"
        },
        {
            "name": "sofort",
            "baseName": "sofort",
            "type": "PaymentMethodDetailsSofort"
        },
        {
            "name": "stripeAccount",
            "baseName": "stripe_account",
            "type": "object"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "object"
        },
        {
            "name": "wechat",
            "baseName": "wechat",
            "type": "object"
        },
        {
            "name": "wechatPay",
            "baseName": "wechat_pay",
            "type": "PaymentMethodDetailsWechatPay"
        }    ];

    static getAttributeTypeMap() {
        return ChargePaymentMethodDetails.attributeTypeMap;
    }
}

