/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiListStripeLineItem } from './apiListStripeLineItem';
import { UpfrontTotalDetails } from './upfrontTotalDetails';

export class ComputedUpfront {
    /**
    * Total before any discounts or taxes are applied.
    */
    'amountSubtotal': number;
    /**
    * Total after discounts and taxes are applied.
    */
    'amountTotal': number;
    'lineItems'?: ApiListStripeLineItem;
    'totalDetails': UpfrontTotalDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountSubtotal",
            "baseName": "amount_subtotal",
            "type": "number"
        },
        {
            "name": "amountTotal",
            "baseName": "amount_total",
            "type": "number"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "ApiListStripeLineItem"
        },
        {
            "name": "totalDetails",
            "baseName": "total_details",
            "type": "UpfrontTotalDetails"
        }    ];

    static getAttributeTypeMap() {
        return ComputedUpfront.attributeTypeMap;
    }
}

