/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum CompanyStructure {
    FREE_ZONE_ESTABLISHMENT = <any> 'free_zone_establishment',
    FREE_ZONE_LLC = <any> 'free_zone_llc',
    GOVERNMENT_INSTRUMENTALITY = <any> 'government_instrumentality',
    GOVERNMENTAL_UNIT = <any> 'governmental_unit',
    INCORPORATED_NON_PROFIT = <any> 'incorporated_non_profit',
    LIMITED_LIABILITY_PARTNERSHIP = <any> 'limited_liability_partnership',
    LLC = <any> 'llc',
    MULTI_MEMBER_LLC = <any> 'multi_member_llc',
    PRIVATE_COMPANY = <any> 'private_company',
    PRIVATE_CORPORATION = <any> 'private_corporation',
    PRIVATE_PARTNERSHIP = <any> 'private_partnership',
    PUBLIC_COMPANY = <any> 'public_company',
    PUBLIC_CORPORATION = <any> 'public_corporation',
    PUBLIC_PARTNERSHIP = <any> 'public_partnership',
    SINGLE_MEMBER_LLC = <any> 'single_member_llc',
    SOLE_ESTABLISHMENT = <any> 'sole_establishment',
    SOLE_PROPRIETORSHIP = <any> 'sole_proprietorship',
    TAX_EXEMPT_GOVERNMENT_INSTRUMENTALITY = <any> 'tax_exempt_government_instrumentality',
    UNINCORPORATED_ASSOCIATION = <any> 'unincorporated_association',
    UNINCORPORATED_NON_PROFIT = <any> 'unincorporated_non_profit'
}
