/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomerTaxLocation } from './customerTaxLocation';
import { TaxAutomaticTax } from './taxAutomaticTax';

export class CustomerTax {
    'automaticTax': TaxAutomaticTax;
    /**
    * A recent IP address of the customer used for tax reporting and tax location inference.
    */
    'ipAddress': string | null;
    'location': CustomerTaxLocation | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "automaticTax",
            "baseName": "automatic_tax",
            "type": "TaxAutomaticTax"
        },
        {
            "name": "ipAddress",
            "baseName": "ip_address",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "CustomerTaxLocation"
        }    ];

    static getAttributeTypeMap() {
        return CustomerTax.attributeTypeMap;
    }
}

export namespace CustomerTax {
}
