/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FinancialAddressIban } from './financialAddressIban';
import { FinancialAddressSortCode } from './financialAddressSortCode';
import { FinancialAddressSpei } from './financialAddressSpei';
import { FinancialAddressSupportedNetwork } from './financialAddressSupportedNetwork';
import { FinancialAddressType } from './financialAddressType';
import { FinancialAddressZengin } from './financialAddressZengin';

export class DisplayBankTransferInstructionsFinancialAddress {
    'iban'?: FinancialAddressIban;
    'sortCode'?: FinancialAddressSortCode;
    'spei'?: FinancialAddressSpei;
    /**
    * The payment networks supported by this FinancialAddress
    */
    'supportedNetworks'?: Array<FinancialAddressSupportedNetwork>;
    'type': FinancialAddressType;
    'zengin'?: FinancialAddressZengin;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iban",
            "baseName": "iban",
            "type": "FinancialAddressIban"
        },
        {
            "name": "sortCode",
            "baseName": "sort_code",
            "type": "FinancialAddressSortCode"
        },
        {
            "name": "spei",
            "baseName": "spei",
            "type": "FinancialAddressSpei"
        },
        {
            "name": "supportedNetworks",
            "baseName": "supported_networks",
            "type": "Array<FinancialAddressSupportedNetwork>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "FinancialAddressType"
        },
        {
            "name": "zengin",
            "baseName": "zengin",
            "type": "FinancialAddressZengin"
        }    ];

    static getAttributeTypeMap() {
        return DisplayBankTransferInstructionsFinancialAddress.attributeTypeMap;
    }
}

export namespace DisplayBankTransferInstructionsFinancialAddress {
}
