/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DisplayBankTransferInstructionsType {
    EU_BANK_TRANSFER = <any> 'eu_bank_transfer',
    GB_BANK_TRANSFER = <any> 'gb_bank_transfer',
    JP_BANK_TRANSFER = <any> 'jp_bank_transfer',
    MX_BANK_TRANSFER = <any> 'mx_bank_transfer'
}
