/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum EpsBank {
    ARZTE_UND_APOTHEKER_BANK = <any> 'arzte_und_apotheker_bank',
    AUSTRIAN_ANADI_BANK_AG = <any> 'austrian_anadi_bank_ag',
    BANK_AUSTRIA = <any> 'bank_austria',
    BANKHAUS_CARL_SPANGLER = <any> 'bankhaus_carl_spangler',
    BANKHAUS_SCHELHAMMER_UND_SCHATTERA_AG = <any> 'bankhaus_schelhammer_und_schattera_ag',
    BAWAG_PSK_AG = <any> 'bawag_psk_ag',
    BKS_BANK_AG = <any> 'bks_bank_ag',
    BRULL_KALLMUS_BANK_AG = <any> 'brull_kallmus_bank_ag',
    BTV_VIER_LANDER_BANK = <any> 'btv_vier_lander_bank',
    CAPITAL_BANK_GRAWE_GRUPPE_AG = <any> 'capital_bank_grawe_gruppe_ag',
    DEUTSCHE_BANK_AG = <any> 'deutsche_bank_ag',
    DOLOMITENBANK = <any> 'dolomitenbank',
    EASYBANK_AG = <any> 'easybank_ag',
    ERSTE_BANK_UND_SPARKASSEN = <any> 'erste_bank_und_sparkassen',
    HYPO_ALPEADRIABANK_INTERNATIONAL_AG = <any> 'hypo_alpeadriabank_international_ag',
    HYPO_BANK_BURGENLAND_AKTIENGESELLSCHAFT = <any> 'hypo_bank_burgenland_aktiengesellschaft',
    HYPO_NOE_LB_FUR_NIEDEROSTERREICH_U_WIEN = <any> 'hypo_noe_lb_fur_niederosterreich_u_wien',
    HYPO_OBEROSTERREICH_SALZBURG_STEIERMARK = <any> 'hypo_oberosterreich_salzburg_steiermark',
    HYPO_TIROL_BANK_AG = <any> 'hypo_tirol_bank_ag',
    HYPO_VORARLBERG_BANK_AG = <any> 'hypo_vorarlberg_bank_ag',
    MARCHFELDER_BANK = <any> 'marchfelder_bank',
    OBERBANK_AG = <any> 'oberbank_ag',
    RAIFFEISEN_BANKENGRUPPE_OSTERREICH = <any> 'raiffeisen_bankengruppe_osterreich',
    SCHOELLERBANK_AG = <any> 'schoellerbank_ag',
    SPARDA_BANK_WIEN = <any> 'sparda_bank_wien',
    VOLKSBANK_GRUPPE = <any> 'volksbank_gruppe',
    VOLKSKREDITBANK_AG = <any> 'volkskreditbank_ag',
    VR_BANK_BRAUNAU = <any> 'vr_bank_braunau'
}
