/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ErrorCode {
    INVALID_ADDRESS_CITY_STATE_POSTAL_CODE = <any> 'invalid_address_city_state_postal_code',
    INVALID_DOB_AGE_UNDER_18 = <any> 'invalid_dob_age_under_18',
    INVALID_REPRESENTATIVE_COUNTRY = <any> 'invalid_representative_country',
    INVALID_STREET_ADDRESS = <any> 'invalid_street_address',
    INVALID_TOS_ACCEPTANCE = <any> 'invalid_tos_acceptance',
    INVALID_VALUE_OTHER = <any> 'invalid_value_other',
    VERIFICATION_DOCUMENT_ADDRESS_MISMATCH = <any> 'verification_document_address_mismatch',
    VERIFICATION_DOCUMENT_ADDRESS_MISSING = <any> 'verification_document_address_missing',
    VERIFICATION_DOCUMENT_CORRUPT = <any> 'verification_document_corrupt',
    VERIFICATION_DOCUMENT_COUNTRY_NOT_SUPPORTED = <any> 'verification_document_country_not_supported',
    VERIFICATION_DOCUMENT_DOB_MISMATCH = <any> 'verification_document_dob_mismatch',
    VERIFICATION_DOCUMENT_DUPLICATE_TYPE = <any> 'verification_document_duplicate_type',
    VERIFICATION_DOCUMENT_EXPIRED = <any> 'verification_document_expired',
    VERIFICATION_DOCUMENT_FAILED_COPY = <any> 'verification_document_failed_copy',
    VERIFICATION_DOCUMENT_FAILED_GREYSCALE = <any> 'verification_document_failed_greyscale',
    VERIFICATION_DOCUMENT_FAILED_OTHER = <any> 'verification_document_failed_other',
    VERIFICATION_DOCUMENT_FAILED_TEST_MODE = <any> 'verification_document_failed_test_mode',
    VERIFICATION_DOCUMENT_FRAUDULENT = <any> 'verification_document_fraudulent',
    VERIFICATION_DOCUMENT_ID_NUMBER_MISMATCH = <any> 'verification_document_id_number_mismatch',
    VERIFICATION_DOCUMENT_ID_NUMBER_MISSING = <any> 'verification_document_id_number_missing',
    VERIFICATION_DOCUMENT_INCOMPLETE = <any> 'verification_document_incomplete',
    VERIFICATION_DOCUMENT_INVALID = <any> 'verification_document_invalid',
    VERIFICATION_DOCUMENT_ISSUE_OR_EXPIRY_DATE_MISSING = <any> 'verification_document_issue_or_expiry_date_missing',
    VERIFICATION_DOCUMENT_MANIPULATED = <any> 'verification_document_manipulated',
    VERIFICATION_DOCUMENT_MISSING_BACK = <any> 'verification_document_missing_back',
    VERIFICATION_DOCUMENT_MISSING_FRONT = <any> 'verification_document_missing_front',
    VERIFICATION_DOCUMENT_NAME_MISMATCH = <any> 'verification_document_name_mismatch',
    VERIFICATION_DOCUMENT_NAME_MISSING = <any> 'verification_document_name_missing',
    VERIFICATION_DOCUMENT_NATIONALITY_MISMATCH = <any> 'verification_document_nationality_mismatch',
    VERIFICATION_DOCUMENT_NOT_READABLE = <any> 'verification_document_not_readable',
    VERIFICATION_DOCUMENT_NOT_SIGNED = <any> 'verification_document_not_signed',
    VERIFICATION_DOCUMENT_NOT_UPLOADED = <any> 'verification_document_not_uploaded',
    VERIFICATION_DOCUMENT_PHOTO_MISMATCH = <any> 'verification_document_photo_mismatch',
    VERIFICATION_DOCUMENT_TOO_LARGE = <any> 'verification_document_too_large',
    VERIFICATION_DOCUMENT_TYPE_NOT_SUPPORTED = <any> 'verification_document_type_not_supported',
    VERIFICATION_FAILED_ADDRESS_MATCH = <any> 'verification_failed_address_match',
    VERIFICATION_FAILED_BUSINESS_IEC_NUMBER = <any> 'verification_failed_business_iec_number',
    VERIFICATION_FAILED_DOCUMENT_MATCH = <any> 'verification_failed_document_match',
    VERIFICATION_FAILED_ID_NUMBER_MATCH = <any> 'verification_failed_id_number_match',
    VERIFICATION_FAILED_KEYED_IDENTITY = <any> 'verification_failed_keyed_identity',
    VERIFICATION_FAILED_KEYED_MATCH = <any> 'verification_failed_keyed_match',
    VERIFICATION_FAILED_NAME_MATCH = <any> 'verification_failed_name_match',
    VERIFICATION_FAILED_OTHER = <any> 'verification_failed_other',
    VERIFICATION_FAILED_RESIDENTIAL_ADDRESS = <any> 'verification_failed_residential_address',
    VERIFICATION_FAILED_TAX_ID_MATCH = <any> 'verification_failed_tax_id_match',
    VERIFICATION_FAILED_TAX_ID_NOT_ISSUED = <any> 'verification_failed_tax_id_not_issued',
    VERIFICATION_MISSING_EXECUTIVES = <any> 'verification_missing_executives',
    VERIFICATION_MISSING_OWNERS = <any> 'verification_missing_owners',
    VERIFICATION_REQUIRES_ADDITIONAL_MEMORANDUM_OF_ASSOCIATIONS = <any> 'verification_requires_additional_memorandum_of_associations'
}
