/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FinancialAddressSpei {
    /**
    * The three-digit bank code
    */
    'bankCode': string;
    /**
    * The short banking institution name
    */
    'bankName': string;
    /**
    * The CLABE number
    */
    'clabe': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bankCode",
            "baseName": "bank_code",
            "type": "string"
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string"
        },
        {
            "name": "clabe",
            "baseName": "clabe",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FinancialAddressSpei.attributeTypeMap;
    }
}

