/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum IdealBic {
    ABNANL2_A = <any> 'ABNANL2A',
    ASNBNL21 = <any> 'ASNBNL21',
    BUNQNL2_A = <any> 'BUNQNL2A',
    FVLBNL22 = <any> 'FVLBNL22',
    HANDNL2_A = <any> 'HANDNL2A',
    INGBNL2_A = <any> 'INGBNL2A',
    KNABNL2_H = <any> 'KNABNL2H',
    MOYONL21 = <any> 'MOYONL21',
    RABONL2_U = <any> 'RABONL2U',
    RBRBNL21 = <any> 'RBRBNL21',
    REVOLT21 = <any> 'REVOLT21',
    SNSBNL2_A = <any> 'SNSBNL2A',
    TRIONL2_U = <any> 'TRIONL2U'
}
