/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum InteracPresentReadMethod {
    CONTACT_EMV = <any> 'contact_emv',
    CONTACTLESS_EMV = <any> 'contactless_emv',
    CONTACTLESS_MAGSTRIPE_MODE = <any> 'contactless_magstripe_mode',
    MAGNETIC_STRIPE_FALLBACK = <any> 'magnetic_stripe_fallback',
    MAGNETIC_STRIPE_TRACK2 = <any> 'magnetic_stripe_track2'
}
