/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentSettingsPaymentMethodOptionsAcssDebit } from './paymentSettingsPaymentMethodOptionsAcssDebit';
import { PaymentSettingsPaymentMethodOptionsBancontact } from './paymentSettingsPaymentMethodOptionsBancontact';
import { PaymentSettingsPaymentMethodOptionsCard } from './paymentSettingsPaymentMethodOptionsCard';
import { PaymentSettingsPaymentMethodOptionsCustomerBalance } from './paymentSettingsPaymentMethodOptionsCustomerBalance';
import { PaymentSettingsPaymentMethodOptionsUsBankAccount } from './paymentSettingsPaymentMethodOptionsUsBankAccount';

/**
* Payment-method-specific configuration to provide to the invoice\'s PaymentIntent.
*/
export class InvoicePaymentSettingsPaymentMethodOptions {
    'acssDebit': PaymentSettingsPaymentMethodOptionsAcssDebit | null;
    'bancontact': PaymentSettingsPaymentMethodOptionsBancontact | null;
    'card': PaymentSettingsPaymentMethodOptionsCard | null;
    'customerBalance': PaymentSettingsPaymentMethodOptionsCustomerBalance | null;
    /**
    * If paying by `konbini`, this sub-hash contains details about the Konbini payment method options to pass to the invoice\'s PaymentIntent.
    */
    'konbini': object | null;
    'usBankAccount': PaymentSettingsPaymentMethodOptionsUsBankAccount | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acssDebit",
            "baseName": "acss_debit",
            "type": "PaymentSettingsPaymentMethodOptionsAcssDebit"
        },
        {
            "name": "bancontact",
            "baseName": "bancontact",
            "type": "PaymentSettingsPaymentMethodOptionsBancontact"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "PaymentSettingsPaymentMethodOptionsCard"
        },
        {
            "name": "customerBalance",
            "baseName": "customer_balance",
            "type": "PaymentSettingsPaymentMethodOptionsCustomerBalance"
        },
        {
            "name": "konbini",
            "baseName": "konbini",
            "type": "object"
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "PaymentSettingsPaymentMethodOptionsUsBankAccount"
        }    ];

    static getAttributeTypeMap() {
        return InvoicePaymentSettingsPaymentMethodOptions.attributeTypeMap;
    }
}

