/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceLineItemDiscountAmountDiscount } from './invoiceLineItemDiscountAmountDiscount';

export class InvoiceTotalDiscountAmount {
    /**
    * The amount, in %s, of the discount.
    */
    'amount': number;
    'discount': InvoiceLineItemDiscountAmountDiscount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "InvoiceLineItemDiscountAmountDiscount"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceTotalDiscountAmount.attributeTypeMap;
    }
}

