/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum LastFinalizationErrorType {
    API_ERROR = <any> 'api_error',
    CARD_ERROR = <any> 'card_error',
    IDEMPOTENCY_ERROR = <any> 'idempotency_error',
    INVALID_REQUEST_ERROR = <any> 'invalid_request_error'
}
