/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VerifyWithMicrodepositsMicrodepositType } from './verifyWithMicrodepositsMicrodepositType';

export class NextActionVerifyWithMicrodeposits {
    /**
    * The timestamp when the microdeposits are expected to land.
    */
    'arrivalDate': number;
    /**
    * The URL for the hosted verification page, which allows customers to verify their bank account.
    */
    'hostedVerificationUrl': string;
    /**
    * The type of the microdeposit sent to the customer. Used to distinguish between different verification methods.
    */
    'microdepositType': VerifyWithMicrodepositsMicrodepositType | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "arrivalDate",
            "baseName": "arrival_date",
            "type": "number"
        },
        {
            "name": "hostedVerificationUrl",
            "baseName": "hosted_verification_url",
            "type": "string"
        },
        {
            "name": "microdepositType",
            "baseName": "microdeposit_type",
            "type": "VerifyWithMicrodepositsMicrodepositType"
        }    ];

    static getAttributeTypeMap() {
        return NextActionVerifyWithMicrodeposits.attributeTypeMap;
    }
}

