/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NextActionBoletoDisplayDetails {
    /**
    * The timestamp after which the boleto expires.
    */
    'expiresAt': number | null;
    /**
    * The URL to the hosted boleto voucher page, which allows customers to view the boleto voucher.
    */
    'hostedVoucherUrl': string | null;
    /**
    * The boleto number.
    */
    'number': string | null;
    /**
    * The URL to the downloadable boleto voucher PDF.
    */
    'pdf': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "hostedVoucherUrl",
            "baseName": "hosted_voucher_url",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "pdf",
            "baseName": "pdf",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NextActionBoletoDisplayDetails.attributeTypeMap;
    }
}

