/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum P24Bank {
    ALIOR_BANK = <any> 'alior_bank',
    BANK_MILLENNIUM = <any> 'bank_millennium',
    BANK_NOWY_BFG_SA = <any> 'bank_nowy_bfg_sa',
    BANK_PEKAO_SA = <any> 'bank_pekao_sa',
    BANKI_SPBDZIELCZE = <any> 'banki_spbdzielcze',
    BLIK = <any> 'blik',
    BNP_PARIBAS = <any> 'bnp_paribas',
    BOZ = <any> 'boz',
    CITI_HANDLOWY = <any> 'citi_handlowy',
    CREDIT_AGRICOLE = <any> 'credit_agricole',
    ENVELOBANK = <any> 'envelobank',
    ETRANSFER_POCZTOWY24 = <any> 'etransfer_pocztowy24',
    GETIN_BANK = <any> 'getin_bank',
    IDEABANK = <any> 'ideabank',
    ING = <any> 'ing',
    INTELIGO = <any> 'inteligo',
    MBANK_MTRANSFER = <any> 'mbank_mtransfer',
    NEST_PRZELEW = <any> 'nest_przelew',
    NOBLE_PAY = <any> 'noble_pay',
    PBAC_Z_IPKO = <any> 'pbac_z_ipko',
    PLUS_BANK = <any> 'plus_bank',
    SANTANDER_PRZELEW24 = <any> 'santander_przelew24',
    TMOBILE_USBUGI_BANKOWE = <any> 'tmobile_usbugi_bankowe',
    TOYOTA_BANK = <any> 'toyota_bank',
    VOLKSWAGEN_BANK = <any> 'volkswagen_bank'
}
