/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdealBank } from './idealBank';
import { IdealBic } from './idealBic';

export class PaymentMethodIdeal {
    /**
    * The customer\'s bank, if provided. Can be one of `abn_amro`, `asn_bank`, `bunq`, `handelsbanken`, `ing`, `knab`, `moneyou`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, or `van_lanschot`.
    */
    'bank': IdealBank | null;
    /**
    * The Bank Identifier Code of the customer\'s bank, if the bank was provided.
    */
    'bic': IdealBic | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bank",
            "baseName": "bank",
            "type": "IdealBank"
        },
        {
            "name": "bic",
            "baseName": "bic",
            "type": "IdealBic"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodIdeal.attributeTypeMap;
    }
}

