/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SofortPreferredLanguage } from './sofortPreferredLanguage';
import { SofortSetupFutureUsage } from './sofortSetupFutureUsage';

export class PaymentMethodOptionsSofort {
    /**
    * Preferred language of the SOFORT authorization page that the customer is redirected to.
    */
    'preferredLanguage': SofortPreferredLanguage | null;
    'setupFutureUsage'?: SofortSetupFutureUsage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preferredLanguage",
            "baseName": "preferred_language",
            "type": "SofortPreferredLanguage"
        },
        {
            "name": "setupFutureUsage",
            "baseName": "setup_future_usage",
            "type": "SofortSetupFutureUsage"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodOptionsSofort.attributeTypeMap;
    }
}

