/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PaymentMethodDetailsSepaCreditTransfer {
    /**
    * Name of the bank associated with the bank account.
    */
    'bankName': string | null;
    /**
    * Bank Identifier Code of the bank associated with the bank account.
    */
    'bic': string | null;
    /**
    * IBAN of the bank account to transfer funds to.
    */
    'iban': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string"
        },
        {
            "name": "bic",
            "baseName": "bic",
            "type": "string"
        },
        {
            "name": "iban",
            "baseName": "iban",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsSepaCreditTransfer.attributeTypeMap;
    }
}

