/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlikOffSession } from './blikOffSession';
import { BlikType } from './blikType';

export class PaymentMethodDetailsBlik {
    /**
    * Date at which the mandate expires.
    */
    'expiresAfter': number | null;
    'offSession'?: BlikOffSession;
    /**
    * Type of the mandate.
    */
    'type': BlikType | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAfter",
            "baseName": "expires_after",
            "type": "number"
        },
        {
            "name": "offSession",
            "baseName": "off_session",
            "type": "BlikOffSession"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BlikType"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsBlik.attributeTypeMap;
    }
}

