/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PaymentMethodDetailsAlipay {
    /**
    * Uniquely identifies this particular Alipay account. You can use this attribute to check whether two Alipay accounts are the same.
    */
    'buyerId'?: string;
    /**
    * Uniquely identifies this particular Alipay account. You can use this attribute to check whether two Alipay accounts are the same.
    */
    'fingerprint': string | null;
    /**
    * Transaction ID of this particular Alipay transaction.
    */
    'transactionId': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerId",
            "baseName": "buyer_id",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsAlipay.attributeTypeMap;
    }
}

