/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NetworksSupported } from './networksSupported';

/**
* Contains information about US bank account networks that can be used.
*/
export class PaymentMethodUsBankAccountNetworks {
    /**
    * The preferred network.
    */
    'preferred': string | null;
    /**
    * All supported networks.
    */
    'supported': Array<NetworksSupported>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preferred",
            "baseName": "preferred",
            "type": "string"
        },
        {
            "name": "supported",
            "baseName": "supported",
            "type": "Array<NetworksSupported>"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodUsBankAccountNetworks.attributeTypeMap;
    }
}

