/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodUsBankAccountNetworks } from './paymentMethodUsBankAccountNetworks';
import { UsBankAccountAccountHolderType } from './usBankAccountAccountHolderType';
import { UsBankAccountAccountType } from './usBankAccountAccountType';

export class PaymentMethodUsBankAccount {
    /**
    * Account holder type: individual or company.
    */
    'accountHolderType': UsBankAccountAccountHolderType | null;
    /**
    * Account type: checkings or savings. Defaults to checking if omitted.
    */
    'accountType': UsBankAccountAccountType | null;
    /**
    * The name of the bank.
    */
    'bankName': string | null;
    /**
    * The ID of the Financial Connections Account used to create the payment method.
    */
    'financialConnectionsAccount'?: string | null;
    /**
    * Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    */
    'fingerprint': string | null;
    /**
    * Last four digits of the bank account number.
    */
    'last4': string | null;
    'networks': PaymentMethodUsBankAccountNetworks | null;
    /**
    * Routing number of the bank account.
    */
    'routingNumber': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolderType",
            "baseName": "account_holder_type",
            "type": "UsBankAccountAccountHolderType"
        },
        {
            "name": "accountType",
            "baseName": "account_type",
            "type": "UsBankAccountAccountType"
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string"
        },
        {
            "name": "financialConnectionsAccount",
            "baseName": "financial_connections_account",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        },
        {
            "name": "networks",
            "baseName": "networks",
            "type": "PaymentMethodUsBankAccountNetworks"
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodUsBankAccount.attributeTypeMap;
    }
}

