/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UsBankAccountFinancialConnections } from './usBankAccountFinancialConnections';
import { UsBankAccountVerificationMethod } from './usBankAccountVerificationMethod';

/**
* If paying by `us_bank_account`, this sub-hash contains details about the ACH direct debit payment method options to pass to the invoice\'s PaymentIntent.
*/
export class PaymentSettingsPaymentMethodOptionsUsBankAccount {
    'financialConnections'?: UsBankAccountFinancialConnections;
    'verificationMethod'?: UsBankAccountVerificationMethod;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "financialConnections",
            "baseName": "financial_connections",
            "type": "UsBankAccountFinancialConnections"
        },
        {
            "name": "verificationMethod",
            "baseName": "verification_method",
            "type": "UsBankAccountVerificationMethod"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSettingsPaymentMethodOptionsUsBankAccount.attributeTypeMap;
    }
}

