/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlipaySetupFutureUsage } from './alipaySetupFutureUsage';

export class PaymentMethodOptionsAlipay {
    'setupFutureUsage'?: AlipaySetupFutureUsage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "setupFutureUsage",
            "baseName": "setup_future_usage",
            "type": "AlipaySetupFutureUsage"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodOptionsAlipay.attributeTypeMap;
    }
}

export namespace PaymentMethodOptionsAlipay {
}
