/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SepaDebitGeneratedFromCharge } from './sepaDebitGeneratedFromCharge';
import { SepaDebitGeneratedFromSetupAttempt } from './sepaDebitGeneratedFromSetupAttempt';

/**
* Information about the object that generated this PaymentMethod.
*/
export class PaymentMethodSepaDebitGeneratedFrom {
    'charge': SepaDebitGeneratedFromCharge | null;
    'setupAttempt': SepaDebitGeneratedFromSetupAttempt | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "charge",
            "baseName": "charge",
            "type": "SepaDebitGeneratedFromCharge"
        },
        {
            "name": "setupAttempt",
            "baseName": "setup_attempt",
            "type": "SepaDebitGeneratedFromSetupAttempt"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodSepaDebitGeneratedFrom.attributeTypeMap;
    }
}

