/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PayoutsSchedule {
    /**
    * The number of days charges for the account will be held before being paid out.
    */
    'delayDays': number;
    /**
    * How frequently funds will be paid out. One of `manual` (payouts only created via API call), `daily`, `weekly`, or `monthly`.
    */
    'interval': string;
    /**
    * The day of the month funds will be paid out. Only shown if `interval` is monthly. Payouts scheduled between the 29th and 31st of the month are sent on the last day of shorter months.
    */
    'monthlyAnchor'?: number;
    /**
    * The day of the week funds will be paid out, of the style \'monday\', \'tuesday\', etc. Only shown if `interval` is weekly.
    */
    'weeklyAnchor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "delayDays",
            "baseName": "delay_days",
            "type": "number"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string"
        },
        {
            "name": "monthlyAnchor",
            "baseName": "monthly_anchor",
            "type": "number"
        },
        {
            "name": "weeklyAnchor",
            "baseName": "weekly_anchor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayoutsSchedule.attributeTypeMap;
    }
}

