/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VerificationAdditionalDocumentBack } from './verificationAdditionalDocumentBack';
import { VerificationAdditionalDocumentFront } from './verificationAdditionalDocumentFront';

/**
* A document showing address, either a passport, local ID card, or utility bill from a well-known utility company.
*/
export class PersonVerificationAdditionalDocument {
    'back': VerificationAdditionalDocumentBack | null;
    /**
    * A user-displayable string describing the verification state of this document. For example, if a document is uploaded and the picture is too fuzzy, this may say \"Identity document is too unclear to read\".
    */
    'details': string | null;
    /**
    * One of `document_corrupt`, `document_country_not_supported`, `document_expired`, `document_failed_copy`, `document_failed_other`, `document_failed_test_mode`, `document_fraudulent`, `document_failed_greyscale`, `document_incomplete`, `document_invalid`, `document_manipulated`, `document_missing_back`, `document_missing_front`, `document_not_readable`, `document_not_uploaded`, `document_photo_mismatch`, `document_too_large`, or `document_type_not_supported`. A machine-readable code specifying the verification state for this document.
    */
    'detailsCode': string | null;
    'front': VerificationAdditionalDocumentFront | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "back",
            "baseName": "back",
            "type": "VerificationAdditionalDocumentBack"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string"
        },
        {
            "name": "detailsCode",
            "baseName": "details_code",
            "type": "string"
        },
        {
            "name": "front",
            "baseName": "front",
            "type": "VerificationAdditionalDocumentFront"
        }    ];

    static getAttributeTypeMap() {
        return PersonVerificationAdditionalDocument.attributeTypeMap;
    }
}

