/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PhaseAddInvoiceItemPrice } from './phaseAddInvoiceItemPrice';
import { StripeTaxRate } from './stripeTaxRate';

export class PhaseAddInvoiceItem {
    'price': PhaseAddInvoiceItemPrice;
    /**
    * The quantity of the invoice item.
    */
    'quantity': number | null;
    /**
    * The tax rates which apply to the item. When set, the `default_tax_rates` do not apply to this item.
    */
    'taxRates'?: Array<StripeTaxRate> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "PhaseAddInvoiceItemPrice"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "taxRates",
            "baseName": "tax_rates",
            "type": "Array<StripeTaxRate>"
        }    ];

    static getAttributeTypeMap() {
        return PhaseAddInvoiceItem.attributeTypeMap;
    }
}

