/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProrationDetailsCreditedItems {
    /**
    * Invoice containing the credited invoice line items
    */
    'invoice': string;
    /**
    * Credited invoice line items
    */
    'invoiceLineItems': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "string"
        },
        {
            "name": "invoiceLineItems",
            "baseName": "invoice_line_items",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ProrationDetailsCreditedItems.attributeTypeMap;
    }
}

