/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReferralSummary {
    'earned': number;
    'inviteCount': number;
    'acceptCount': number;
    'referredBy'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "earned",
            "baseName": "earned",
            "type": "number"
        },
        {
            "name": "inviteCount",
            "baseName": "inviteCount",
            "type": "number"
        },
        {
            "name": "acceptCount",
            "baseName": "acceptCount",
            "type": "number"
        },
        {
            "name": "referredBy",
            "baseName": "referredBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReferralSummary.attributeTypeMap;
    }
}

