/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayDetailsEmailSent } from './displayDetailsEmailSent';

/**
* Contains the refund details.
*/
export class RefundNextActionDisplayDetails {
    'emailSent': DisplayDetailsEmailSent;
    /**
    * The expiry timestamp.
    */
    'expiresAt': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailSent",
            "baseName": "email_sent",
            "type": "DisplayDetailsEmailSent"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RefundNextActionDisplayDetails.attributeTypeMap;
    }
}

