/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodDetailsBancontact } from './paymentMethodDetailsBancontact';
import { PaymentMethodDetailsBlik } from './paymentMethodDetailsBlik';
import { PaymentMethodDetailsCardPresent } from './paymentMethodDetailsCardPresent';
import { PaymentMethodDetailsIdeal } from './paymentMethodDetailsIdeal';
import { PaymentMethodDetailsSepaDebit } from './paymentMethodDetailsSepaDebit';
import { PaymentMethodDetailsSofort } from './paymentMethodDetailsSofort';

export class SetupAttemptPaymentMethodDetails {
    'acssDebit'?: object;
    'auBecsDebit'?: object;
    'bacsDebit'?: object;
    'bancontact'?: PaymentMethodDetailsBancontact;
    'blik'?: PaymentMethodDetailsBlik;
    'boleto'?: object;
    'card'?: object;
    'cardPresent'?: PaymentMethodDetailsCardPresent;
    'ideal'?: PaymentMethodDetailsIdeal;
    'klarna'?: object;
    'link'?: object;
    'sepaDebit'?: PaymentMethodDetailsSepaDebit;
    'sofort'?: PaymentMethodDetailsSofort;
    /**
    * The type of the payment method used in the SetupIntent (e.g., `card`). An additional hash is included on `payment_method_details` with a name matching this value. It contains confirmation-specific information for the payment method.
    */
    'type': string;
    'usBankAccount'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acssDebit",
            "baseName": "acss_debit",
            "type": "object"
        },
        {
            "name": "auBecsDebit",
            "baseName": "au_becs_debit",
            "type": "object"
        },
        {
            "name": "bacsDebit",
            "baseName": "bacs_debit",
            "type": "object"
        },
        {
            "name": "bancontact",
            "baseName": "bancontact",
            "type": "PaymentMethodDetailsBancontact"
        },
        {
            "name": "blik",
            "baseName": "blik",
            "type": "PaymentMethodDetailsBlik"
        },
        {
            "name": "boleto",
            "baseName": "boleto",
            "type": "object"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "object"
        },
        {
            "name": "cardPresent",
            "baseName": "card_present",
            "type": "PaymentMethodDetailsCardPresent"
        },
        {
            "name": "ideal",
            "baseName": "ideal",
            "type": "PaymentMethodDetailsIdeal"
        },
        {
            "name": "klarna",
            "baseName": "klarna",
            "type": "object"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "object"
        },
        {
            "name": "sepaDebit",
            "baseName": "sepa_debit",
            "type": "PaymentMethodDetailsSepaDebit"
        },
        {
            "name": "sofort",
            "baseName": "sofort",
            "type": "PaymentMethodDetailsSofort"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return SetupAttemptPaymentMethodDetails.attributeTypeMap;
    }
}

