/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodOptionsAcssDebit } from './paymentMethodOptionsAcssDebit';
import { PaymentMethodOptionsBlik } from './paymentMethodOptionsBlik';
import { PaymentMethodOptionsCard } from './paymentMethodOptionsCard';
import { PaymentMethodOptionsLink } from './paymentMethodOptionsLink';
import { PaymentMethodOptionsSepaDebit } from './paymentMethodOptionsSepaDebit';
import { PaymentMethodOptionsUsBankAccount } from './paymentMethodOptionsUsBankAccount';

export class SetupIntentPaymentMethodOptions {
    'acssDebit'?: PaymentMethodOptionsAcssDebit;
    'blik'?: PaymentMethodOptionsBlik;
    'card'?: PaymentMethodOptionsCard;
    'link'?: PaymentMethodOptionsLink;
    'sepaDebit'?: PaymentMethodOptionsSepaDebit;
    'usBankAccount'?: PaymentMethodOptionsUsBankAccount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acssDebit",
            "baseName": "acss_debit",
            "type": "PaymentMethodOptionsAcssDebit"
        },
        {
            "name": "blik",
            "baseName": "blik",
            "type": "PaymentMethodOptionsBlik"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "PaymentMethodOptionsCard"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "PaymentMethodOptionsLink"
        },
        {
            "name": "sepaDebit",
            "baseName": "sepa_debit",
            "type": "PaymentMethodOptionsSepaDebit"
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "PaymentMethodOptionsUsBankAccount"
        }    ];

    static getAttributeTypeMap() {
        return SetupIntentPaymentMethodOptions.attributeTypeMap;
    }
}

