/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ShippingCarrier {
    DHL = <any> 'dhl',
    FEDEX = <any> 'fedex',
    ROYAL_MAIL = <any> 'royal_mail',
    USPS = <any> 'usps'
}
