/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SourceSepaDebit {
    'bankCode'?: string | null;
    'branchCode'?: string | null;
    'country'?: string | null;
    'fingerprint'?: string | null;
    'last4'?: string | null;
    'mandateReference'?: string | null;
    'mandateUrl'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bankCode",
            "baseName": "bank_code",
            "type": "string"
        },
        {
            "name": "branchCode",
            "baseName": "branch_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        },
        {
            "name": "mandateReference",
            "baseName": "mandate_reference",
            "type": "string"
        },
        {
            "name": "mandateUrl",
            "baseName": "mandate_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SourceSepaDebit.attributeTypeMap;
    }
}

