/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The DeletedCustomer object.
*/
export class StripeDeletedCustomer {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeDeletedCustomer.ObjectEnum;
    /**
    * Always true for a deleted object
    */
    'deleted': StripeDeletedCustomer.DeletedEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeDeletedCustomer.ObjectEnum"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "StripeDeletedCustomer.DeletedEnum"
        }    ];

    static getAttributeTypeMap() {
        return StripeDeletedCustomer.attributeTypeMap;
    }
}

export namespace StripeDeletedCustomer {
    export enum ObjectEnum {
        CUSTOMER = <any> 'customer'
    }
    export enum DeletedEnum {
        TRUE = <any> true
    }
}
