/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodOptionsAcssDebit } from './paymentMethodOptionsAcssDebit';
import { PaymentMethodOptionsAffirm } from './paymentMethodOptionsAffirm';
import { PaymentMethodOptionsAfterpayClearpay } from './paymentMethodOptionsAfterpayClearpay';
import { PaymentMethodOptionsAlipay } from './paymentMethodOptionsAlipay';
import { PaymentMethodOptionsAuBecsDebit } from './paymentMethodOptionsAuBecsDebit';
import { PaymentMethodOptionsBacsDebit } from './paymentMethodOptionsBacsDebit';
import { PaymentMethodOptionsBancontact } from './paymentMethodOptionsBancontact';
import { PaymentMethodOptionsBlik } from './paymentMethodOptionsBlik';
import { PaymentMethodOptionsBoleto } from './paymentMethodOptionsBoleto';
import { PaymentMethodOptionsCard } from './paymentMethodOptionsCard';
import { PaymentMethodOptionsCardPresent } from './paymentMethodOptionsCardPresent';
import { PaymentMethodOptionsCustomerBalance } from './paymentMethodOptionsCustomerBalance';
import { PaymentMethodOptionsEps } from './paymentMethodOptionsEps';
import { PaymentMethodOptionsFpx } from './paymentMethodOptionsFpx';
import { PaymentMethodOptionsGiropay } from './paymentMethodOptionsGiropay';
import { PaymentMethodOptionsGrabpay } from './paymentMethodOptionsGrabpay';
import { PaymentMethodOptionsIdeal } from './paymentMethodOptionsIdeal';
import { PaymentMethodOptionsKlarna } from './paymentMethodOptionsKlarna';
import { PaymentMethodOptionsLink } from './paymentMethodOptionsLink';
import { PaymentMethodOptionsOxxo } from './paymentMethodOptionsOxxo';
import { PaymentMethodOptionsP24 } from './paymentMethodOptionsP24';
import { PaymentMethodOptionsPaynow } from './paymentMethodOptionsPaynow';
import { PaymentMethodOptionsPix } from './paymentMethodOptionsPix';
import { PaymentMethodOptionsPromptpay } from './paymentMethodOptionsPromptpay';
import { PaymentMethodOptionsSepaDebit } from './paymentMethodOptionsSepaDebit';
import { PaymentMethodOptionsSofort } from './paymentMethodOptionsSofort';
import { PaymentMethodOptionsUsBankAccount } from './paymentMethodOptionsUsBankAccount';
import { PaymentMethodOptionsWechatPay } from './paymentMethodOptionsWechatPay';

/**
* Payment-method-specific configuration for this PaymentIntent.
*/
export class StripePaymentIntentPaymentMethodOptions {
    'acssDebit'?: PaymentMethodOptionsAcssDebit;
    'affirm'?: PaymentMethodOptionsAffirm;
    'afterpayClearpay'?: PaymentMethodOptionsAfterpayClearpay;
    'alipay'?: PaymentMethodOptionsAlipay;
    'auBecsDebit'?: PaymentMethodOptionsAuBecsDebit;
    'bacsDebit'?: PaymentMethodOptionsBacsDebit;
    'bancontact'?: PaymentMethodOptionsBancontact;
    'blik'?: PaymentMethodOptionsBlik;
    'boleto'?: PaymentMethodOptionsBoleto;
    'card'?: PaymentMethodOptionsCard;
    'cardPresent'?: PaymentMethodOptionsCardPresent;
    'customerBalance'?: PaymentMethodOptionsCustomerBalance;
    'eps'?: PaymentMethodOptionsEps;
    'fpx'?: PaymentMethodOptionsFpx;
    'giropay'?: PaymentMethodOptionsGiropay;
    'grabpay'?: PaymentMethodOptionsGrabpay;
    'ideal'?: PaymentMethodOptionsIdeal;
    'interacPresent'?: object;
    'klarna'?: PaymentMethodOptionsKlarna;
    'konbini'?: object;
    'link'?: PaymentMethodOptionsLink;
    'oxxo'?: PaymentMethodOptionsOxxo;
    'p24'?: PaymentMethodOptionsP24;
    'paynow'?: PaymentMethodOptionsPaynow;
    'pix'?: PaymentMethodOptionsPix;
    'promptpay'?: PaymentMethodOptionsPromptpay;
    'sepaDebit'?: PaymentMethodOptionsSepaDebit;
    'sofort'?: PaymentMethodOptionsSofort;
    'usBankAccount'?: PaymentMethodOptionsUsBankAccount;
    'wechatPay'?: PaymentMethodOptionsWechatPay;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acssDebit",
            "baseName": "acss_debit",
            "type": "PaymentMethodOptionsAcssDebit"
        },
        {
            "name": "affirm",
            "baseName": "affirm",
            "type": "PaymentMethodOptionsAffirm"
        },
        {
            "name": "afterpayClearpay",
            "baseName": "afterpay_clearpay",
            "type": "PaymentMethodOptionsAfterpayClearpay"
        },
        {
            "name": "alipay",
            "baseName": "alipay",
            "type": "PaymentMethodOptionsAlipay"
        },
        {
            "name": "auBecsDebit",
            "baseName": "au_becs_debit",
            "type": "PaymentMethodOptionsAuBecsDebit"
        },
        {
            "name": "bacsDebit",
            "baseName": "bacs_debit",
            "type": "PaymentMethodOptionsBacsDebit"
        },
        {
            "name": "bancontact",
            "baseName": "bancontact",
            "type": "PaymentMethodOptionsBancontact"
        },
        {
            "name": "blik",
            "baseName": "blik",
            "type": "PaymentMethodOptionsBlik"
        },
        {
            "name": "boleto",
            "baseName": "boleto",
            "type": "PaymentMethodOptionsBoleto"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "PaymentMethodOptionsCard"
        },
        {
            "name": "cardPresent",
            "baseName": "card_present",
            "type": "PaymentMethodOptionsCardPresent"
        },
        {
            "name": "customerBalance",
            "baseName": "customer_balance",
            "type": "PaymentMethodOptionsCustomerBalance"
        },
        {
            "name": "eps",
            "baseName": "eps",
            "type": "PaymentMethodOptionsEps"
        },
        {
            "name": "fpx",
            "baseName": "fpx",
            "type": "PaymentMethodOptionsFpx"
        },
        {
            "name": "giropay",
            "baseName": "giropay",
            "type": "PaymentMethodOptionsGiropay"
        },
        {
            "name": "grabpay",
            "baseName": "grabpay",
            "type": "PaymentMethodOptionsGrabpay"
        },
        {
            "name": "ideal",
            "baseName": "ideal",
            "type": "PaymentMethodOptionsIdeal"
        },
        {
            "name": "interacPresent",
            "baseName": "interac_present",
            "type": "object"
        },
        {
            "name": "klarna",
            "baseName": "klarna",
            "type": "PaymentMethodOptionsKlarna"
        },
        {
            "name": "konbini",
            "baseName": "konbini",
            "type": "object"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "PaymentMethodOptionsLink"
        },
        {
            "name": "oxxo",
            "baseName": "oxxo",
            "type": "PaymentMethodOptionsOxxo"
        },
        {
            "name": "p24",
            "baseName": "p24",
            "type": "PaymentMethodOptionsP24"
        },
        {
            "name": "paynow",
            "baseName": "paynow",
            "type": "PaymentMethodOptionsPaynow"
        },
        {
            "name": "pix",
            "baseName": "pix",
            "type": "PaymentMethodOptionsPix"
        },
        {
            "name": "promptpay",
            "baseName": "promptpay",
            "type": "PaymentMethodOptionsPromptpay"
        },
        {
            "name": "sepaDebit",
            "baseName": "sepa_debit",
            "type": "PaymentMethodOptionsSepaDebit"
        },
        {
            "name": "sofort",
            "baseName": "sofort",
            "type": "PaymentMethodOptionsSofort"
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "PaymentMethodOptionsUsBankAccount"
        },
        {
            "name": "wechatPay",
            "baseName": "wechat_pay",
            "type": "PaymentMethodOptionsWechatPay"
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentIntentPaymentMethodOptions.attributeTypeMap;
    }
}

