/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The DeletedBankAccount object.
*/
export class StripeDeletedBankAccount {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeDeletedBankAccount.ObjectEnum;
    /**
    * Three-letter [ISO code for the currency](https://stripe.com/docs/payouts) paid out to the bank account.
    */
    'currency'?: string | null;
    /**
    * Always true for a deleted object
    */
    'deleted': StripeDeletedBankAccount.DeletedEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeDeletedBankAccount.ObjectEnum"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "StripeDeletedBankAccount.DeletedEnum"
        }    ];

    static getAttributeTypeMap() {
        return StripeDeletedBankAccount.attributeTypeMap;
    }
}

export namespace StripeDeletedBankAccount {
    export enum ObjectEnum {
        BANK_ACCOUNT = <any> 'bank_account'
    }
    export enum DeletedEnum {
        TRUE = <any> true
    }
}
