/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripeTaxCode } from './stripeTaxCode';

/**
* A [tax code](https://stripe.com/docs/tax/tax-categories) ID.
*/
export class StripeProductTaxCode {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeProductTaxCode.ObjectEnum;
    /**
    * A detailed description of which types of products the tax code represents.
    */
    'description': string;
    /**
    * A short name for the tax code.
    */
    'name': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeProductTaxCode.ObjectEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StripeProductTaxCode.attributeTypeMap;
    }
}

export namespace StripeProductTaxCode {
    export enum ObjectEnum {
        TAX_CODE = <any> 'tax_code'
    }
}
