/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripePlan } from './stripePlan';
import { StripePrice } from './stripePrice';
import { StripeSubscriptionItemBillingThresholds } from './stripeSubscriptionItemBillingThresholds';
import { StripeTaxRate } from './stripeTaxRate';

/**
* Subscription items allow you to create customer subscriptions with more than one plan, making it easy to represent complex billing relationships.
*/
export class StripeSubscriptionItem {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeSubscriptionItem.ObjectEnum;
    'billingThresholds': StripeSubscriptionItemBillingThresholds | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    'deleted'?: any | null;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; };
    'plan': StripePlan;
    'price': StripePrice;
    /**
    * The [quantity](https://stripe.com/docs/subscriptions/quantities) of the plan to which the customer should be subscribed.
    */
    'quantity'?: number;
    /**
    * The `subscription` this `subscription_item` belongs to.
    */
    'subscription': string;
    /**
    * The tax rates which apply to this `subscription_item`. When set, the `default_tax_rates` on the subscription do not apply to this `subscription_item`.
    */
    'taxRates': Array<StripeTaxRate> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeSubscriptionItem.ObjectEnum"
        },
        {
            "name": "billingThresholds",
            "baseName": "billing_thresholds",
            "type": "StripeSubscriptionItemBillingThresholds"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "StripePlan"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "StripePrice"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "string"
        },
        {
            "name": "taxRates",
            "baseName": "tax_rates",
            "type": "Array<StripeTaxRate>"
        }    ];

    static getAttributeTypeMap() {
        return StripeSubscriptionItem.attributeTypeMap;
    }
}

export namespace StripeSubscriptionItem {
    export enum ObjectEnum {
        SUBSCRIPTION_ITEM = <any> 'subscription_item'
    }
}
