/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReviewClosedReason } from './reviewClosedReason';
import { ReviewOpenedReason } from './reviewOpenedReason';
import { StripeReview } from './stripeReview';
import { StripeReviewCharge } from './stripeReviewCharge';
import { StripeReviewIpAddressLocation } from './stripeReviewIpAddressLocation';
import { StripeReviewPaymentIntent } from './stripeReviewPaymentIntent';
import { StripeReviewSession } from './stripeReviewSession';

/**
* ID of the review associated with this PaymentIntent, if any.
*/
export class StripePaymentIntentReview {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripePaymentIntentReview.ObjectEnum;
    /**
    * The ZIP or postal code of the card used, if applicable.
    */
    'billingZip': string | null;
    'charge': StripeReviewCharge | null;
    /**
    * The reason the review was closed, or null if it has not yet been closed. One of `approved`, `refunded`, `refunded_as_fraud`, `disputed`, or `redacted`.
    */
    'closedReason': ReviewClosedReason | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * The IP address where the payment originated.
    */
    'ipAddress': string | null;
    'ipAddressLocation': StripeReviewIpAddressLocation | null;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * If `true`, the review needs action.
    */
    'open': boolean;
    'openedReason': ReviewOpenedReason;
    'paymentIntent'?: StripeReviewPaymentIntent;
    /**
    * The reason the review is currently open or closed. One of `rule`, `manual`, `approved`, `refunded`, `refunded_as_fraud`, `disputed`, or `redacted`.
    */
    'reason': string;
    'session': StripeReviewSession | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripePaymentIntentReview.ObjectEnum"
        },
        {
            "name": "billingZip",
            "baseName": "billing_zip",
            "type": "string"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "StripeReviewCharge"
        },
        {
            "name": "closedReason",
            "baseName": "closed_reason",
            "type": "ReviewClosedReason"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "ipAddress",
            "baseName": "ip_address",
            "type": "string"
        },
        {
            "name": "ipAddressLocation",
            "baseName": "ip_address_location",
            "type": "StripeReviewIpAddressLocation"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "open",
            "baseName": "open",
            "type": "boolean"
        },
        {
            "name": "openedReason",
            "baseName": "opened_reason",
            "type": "ReviewOpenedReason"
        },
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "StripeReviewPaymentIntent"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "StripeReviewSession"
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentIntentReview.attributeTypeMap;
    }
}

export namespace StripePaymentIntentReview {
    export enum ObjectEnum {
        REVIEW = <any> 'review'
    }
}
