/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SetupAttemptFlowDirection } from './setupAttemptFlowDirection';
import { SetupAttemptPaymentMethodDetails } from './setupAttemptPaymentMethodDetails';
import { StripeSetupAttempt } from './stripeSetupAttempt';
import { StripeSetupAttemptApplication } from './stripeSetupAttemptApplication';
import { StripeSetupAttemptCustomer } from './stripeSetupAttemptCustomer';
import { StripeSetupAttemptOnBehalfOf } from './stripeSetupAttemptOnBehalfOf';
import { StripeSetupAttemptPaymentMethod } from './stripeSetupAttemptPaymentMethod';
import { StripeSetupAttemptSetupError } from './stripeSetupAttemptSetupError';
import { StripeSetupAttemptSetupIntent } from './stripeSetupAttemptSetupIntent';

/**
* The most recent SetupAttempt for this SetupIntent.
*/
export class StripeSetupIntentLatestAttempt {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeSetupIntentLatestAttempt.ObjectEnum;
    'application': StripeSetupAttemptApplication | null;
    /**
    * If present, the SetupIntent\'s payment method will be attached to the in-context Stripe Account.  It can only be used for this Stripe Account\'s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
    */
    'attachToSelf'?: boolean;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    'customer': StripeSetupAttemptCustomer | null;
    /**
    * Indicates the directions of money movement for which this payment method is intended to be used.  Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
    */
    'flowDirections': Array<SetupAttemptFlowDirection> | null;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    'onBehalfOf': StripeSetupAttemptOnBehalfOf | null;
    'paymentMethod': StripeSetupAttemptPaymentMethod;
    'paymentMethodDetails': SetupAttemptPaymentMethodDetails;
    'setupError': StripeSetupAttemptSetupError | null;
    'setupIntent': StripeSetupAttemptSetupIntent;
    /**
    * Status of this SetupAttempt, one of `requires_confirmation`, `requires_action`, `processing`, `succeeded`, `failed`, or `abandoned`.
    */
    'status': string;
    /**
    * The value of [usage](https://stripe.com/docs/api/setup_intents/object#setup_intent_object-usage) on the SetupIntent at the time of this confirmation, one of `off_session` or `on_session`.
    */
    'usage': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeSetupIntentLatestAttempt.ObjectEnum"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "StripeSetupAttemptApplication"
        },
        {
            "name": "attachToSelf",
            "baseName": "attach_to_self",
            "type": "boolean"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "StripeSetupAttemptCustomer"
        },
        {
            "name": "flowDirections",
            "baseName": "flow_directions",
            "type": "Array<SetupAttemptFlowDirection>"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "onBehalfOf",
            "baseName": "on_behalf_of",
            "type": "StripeSetupAttemptOnBehalfOf"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "StripeSetupAttemptPaymentMethod"
        },
        {
            "name": "paymentMethodDetails",
            "baseName": "payment_method_details",
            "type": "SetupAttemptPaymentMethodDetails"
        },
        {
            "name": "setupError",
            "baseName": "setup_error",
            "type": "StripeSetupAttemptSetupError"
        },
        {
            "name": "setupIntent",
            "baseName": "setup_intent",
            "type": "StripeSetupAttemptSetupIntent"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StripeSetupIntentLatestAttempt.attributeTypeMap;
    }
}

export namespace StripeSetupIntentLatestAttempt {
    export enum ObjectEnum {
        SETUP_ATTEMPT = <any> 'setup_attempt'
    }
}
