/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromotionCodeRestrictions } from './promotionCodeRestrictions';
import { StripeCoupon } from './stripeCoupon';
import { StripePromotionCode } from './stripePromotionCode';
import { StripePromotionCodeCustomer } from './stripePromotionCodeCustomer';

/**
* The promotion code applied to create this discount.
*/
export class StripeDiscountPromotionCode {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeDiscountPromotionCode.ObjectEnum;
    /**
    * Whether the promotion code is currently active. A promotion code is only active if the coupon is also valid.
    */
    'active': boolean;
    /**
    * The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for each customer.
    */
    'code': string;
    'coupon': StripeCoupon;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    'customer': StripePromotionCodeCustomer | null;
    /**
    * Date at which the promotion code can no longer be redeemed.
    */
    'expiresAt': number | null;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * Maximum number of times this promotion code can be redeemed.
    */
    'maxRedemptions': number | null;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': any | null;
    'restrictions': PromotionCodeRestrictions;
    /**
    * Number of times this promotion code has been used.
    */
    'timesRedeemed': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeDiscountPromotionCode.ObjectEnum"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "StripeCoupon"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "StripePromotionCodeCustomer"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "maxRedemptions",
            "baseName": "max_redemptions",
            "type": "number"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        },
        {
            "name": "restrictions",
            "baseName": "restrictions",
            "type": "PromotionCodeRestrictions"
        },
        {
            "name": "timesRedeemed",
            "baseName": "times_redeemed",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return StripeDiscountPromotionCode.attributeTypeMap;
    }
}

export namespace StripeDiscountPromotionCode {
    export enum ObjectEnum {
        PROMOTION_CODE = <any> 'promotion_code'
    }
}
