/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisputeEvidence } from './disputeEvidence';
import { DisputeStatus } from './disputeStatus';
import { StripeBalanceTransaction } from './stripeBalanceTransaction';
import { StripeIssuingDisputeTransaction } from './stripeIssuingDisputeTransaction';
import { StripeIssuingDisputeTreasury } from './stripeIssuingDisputeTreasury';

/**
* As a [card issuer](https://stripe.com/docs/issuing), you can dispute transactions that the cardholder does not recognize, suspects to be fraudulent, or has other issues with.  Related guide: [Disputing Transactions](https://stripe.com/docs/issuing/purchases/disputes)
*/
export class StripeIssuingDispute {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeIssuingDispute.ObjectEnum;
    /**
    * Disputed amount in the card\'s currency and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal). Usually the amount of the `transaction`, but can differ (usually because of currency fluctuation).
    */
    'amount': number;
    /**
    * List of balance transactions associated with the dispute.
    */
    'balanceTransactions': Array<StripeBalanceTransaction> | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * The currency the `transaction` was made in.
    */
    'currency': string;
    'evidence': DisputeEvidence;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; };
    'status': DisputeStatus;
    'transaction': StripeIssuingDisputeTransaction;
    'treasury'?: StripeIssuingDisputeTreasury | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeIssuingDispute.ObjectEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "balanceTransactions",
            "baseName": "balance_transactions",
            "type": "Array<StripeBalanceTransaction>"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "evidence",
            "baseName": "evidence",
            "type": "DisputeEvidence"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DisputeStatus"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "StripeIssuingDisputeTransaction"
        },
        {
            "name": "treasury",
            "baseName": "treasury",
            "type": "StripeIssuingDisputeTreasury"
        }    ];

    static getAttributeTypeMap() {
        return StripeIssuingDispute.attributeTypeMap;
    }
}

export namespace StripeIssuingDispute {
    export enum ObjectEnum {
        ISSUING_DISPUTE = <any> 'issuing.dispute'
    }
}
