/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripeFeeRefundBalanceTransaction } from './stripeFeeRefundBalanceTransaction';
import { StripeTransferReversal } from './stripeTransferReversal';
import { StripeTransferReversalDestinationPaymentRefund } from './stripeTransferReversalDestinationPaymentRefund';
import { StripeTransferReversalSourceRefund } from './stripeTransferReversalSourceRefund';
import { StripeTransferReversalTransfer } from './stripeTransferReversalTransfer';

/**
* If the accompanying transfer was reversed, the transfer reversal object. Only applicable if the charge was created using the destination parameter.
*/
export class StripeRefundTransferReversal {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeRefundTransferReversal.ObjectEnum;
    /**
    * Amount, in %s.
    */
    'amount': number;
    'balanceTransaction': StripeFeeRefundBalanceTransaction | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string;
    'destinationPaymentRefund': StripeTransferReversalDestinationPaymentRefund | null;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': any | null;
    'sourceRefund': StripeTransferReversalSourceRefund | null;
    'transfer': StripeTransferReversalTransfer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeRefundTransferReversal.ObjectEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "balanceTransaction",
            "baseName": "balance_transaction",
            "type": "StripeFeeRefundBalanceTransaction"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "destinationPaymentRefund",
            "baseName": "destination_payment_refund",
            "type": "StripeTransferReversalDestinationPaymentRefund"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        },
        {
            "name": "sourceRefund",
            "baseName": "source_refund",
            "type": "StripeTransferReversalSourceRefund"
        },
        {
            "name": "transfer",
            "baseName": "transfer",
            "type": "StripeTransferReversalTransfer"
        }    ];

    static getAttributeTypeMap() {
        return StripeRefundTransferReversal.attributeTypeMap;
    }
}

export namespace StripeRefundTransferReversal {
    export enum ObjectEnum {
        TRANSFER_REVERSAL = <any> 'transfer_reversal'
    }
}
