/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripeDeletedTaxId } from './stripeDeletedTaxId';
import { StripeTaxId } from './stripeTaxId';
import { StripeTaxIdCustomer } from './stripeTaxIdCustomer';
import { StripeTaxIdVerification } from './stripeTaxIdVerification';
import { TaxIdType } from './taxIdType';

export class StripeInvoiceAccountTaxIdsInner {
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeInvoiceAccountTaxIdsInner.ObjectEnum;
    /**
    * Two-letter ISO code representing the country of the tax ID.
    */
    'country': string | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    'customer': StripeTaxIdCustomer | null;
    /**
    * Always true for a deleted object
    */
    'deleted': StripeInvoiceAccountTaxIdsInner.DeletedEnum;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    'type': TaxIdType;
    /**
    * Value of the tax ID.
    */
    'value': string;
    'verification': StripeTaxIdVerification | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeInvoiceAccountTaxIdsInner.ObjectEnum"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "StripeTaxIdCustomer"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "StripeInvoiceAccountTaxIdsInner.DeletedEnum"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TaxIdType"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "verification",
            "baseName": "verification",
            "type": "StripeTaxIdVerification"
        }    ];

    static getAttributeTypeMap() {
        return StripeInvoiceAccountTaxIdsInner.attributeTypeMap;
    }
}

export namespace StripeInvoiceAccountTaxIdsInner {
    export enum ObjectEnum {
        TAX_ID = <any> 'tax_id'
    }
    export enum DeletedEnum {
        TRUE = <any> true
    }
}
