/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NextActionAlipayHandleRedirect } from './nextActionAlipayHandleRedirect';
import { NextActionBoletoDisplayDetails } from './nextActionBoletoDisplayDetails';
import { NextActionCardAwaitNotification } from './nextActionCardAwaitNotification';
import { NextActionDisplayBankTransferInstructions } from './nextActionDisplayBankTransferInstructions';
import { NextActionKonbiniDisplayDetails } from './nextActionKonbiniDisplayDetails';
import { NextActionOxxoDisplayDetails } from './nextActionOxxoDisplayDetails';
import { NextActionPaynowDisplayQrCode } from './nextActionPaynowDisplayQrCode';
import { NextActionPixDisplayQrCode } from './nextActionPixDisplayQrCode';
import { NextActionPromptpayDisplayQrCode } from './nextActionPromptpayDisplayQrCode';
import { NextActionRedirectToUrl } from './nextActionRedirectToUrl';
import { NextActionVerifyWithMicrodeposits } from './nextActionVerifyWithMicrodeposits';
import { NextActionWechatPayDisplayQrCode } from './nextActionWechatPayDisplayQrCode';
import { NextActionWechatPayRedirectToAndroidApp } from './nextActionWechatPayRedirectToAndroidApp';
import { NextActionWechatPayRedirectToIosApp } from './nextActionWechatPayRedirectToIosApp';

/**
* If present, this property tells you what actions you need to take in order for your customer to fulfill a payment using the provided source.
*/
export class StripePaymentIntentNextAction {
    'alipayHandleRedirect'?: NextActionAlipayHandleRedirect;
    'boletoDisplayDetails'?: NextActionBoletoDisplayDetails;
    'cardAwaitNotification'?: NextActionCardAwaitNotification;
    'displayBankTransferInstructions'?: NextActionDisplayBankTransferInstructions;
    'konbiniDisplayDetails'?: NextActionKonbiniDisplayDetails;
    'oxxoDisplayDetails'?: NextActionOxxoDisplayDetails;
    'paynowDisplayQrCode'?: NextActionPaynowDisplayQrCode;
    'pixDisplayQrCode'?: NextActionPixDisplayQrCode;
    'promptpayDisplayQrCode'?: NextActionPromptpayDisplayQrCode;
    'redirectToUrl'?: NextActionRedirectToUrl;
    /**
    * Type of the next action to perform, one of `redirect_to_url`, `use_stripe_sdk`, `alipay_handle_redirect`, `oxxo_display_details`, or `verify_with_microdeposits`.
    */
    'type': string;
    'useStripeSdk'?: object;
    'verifyWithMicrodeposits'?: NextActionVerifyWithMicrodeposits;
    'wechatPayDisplayQrCode'?: NextActionWechatPayDisplayQrCode;
    'wechatPayRedirectToAndroidApp'?: NextActionWechatPayRedirectToAndroidApp;
    'wechatPayRedirectToIosApp'?: NextActionWechatPayRedirectToIosApp;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alipayHandleRedirect",
            "baseName": "alipay_handle_redirect",
            "type": "NextActionAlipayHandleRedirect"
        },
        {
            "name": "boletoDisplayDetails",
            "baseName": "boleto_display_details",
            "type": "NextActionBoletoDisplayDetails"
        },
        {
            "name": "cardAwaitNotification",
            "baseName": "card_await_notification",
            "type": "NextActionCardAwaitNotification"
        },
        {
            "name": "displayBankTransferInstructions",
            "baseName": "display_bank_transfer_instructions",
            "type": "NextActionDisplayBankTransferInstructions"
        },
        {
            "name": "konbiniDisplayDetails",
            "baseName": "konbini_display_details",
            "type": "NextActionKonbiniDisplayDetails"
        },
        {
            "name": "oxxoDisplayDetails",
            "baseName": "oxxo_display_details",
            "type": "NextActionOxxoDisplayDetails"
        },
        {
            "name": "paynowDisplayQrCode",
            "baseName": "paynow_display_qr_code",
            "type": "NextActionPaynowDisplayQrCode"
        },
        {
            "name": "pixDisplayQrCode",
            "baseName": "pix_display_qr_code",
            "type": "NextActionPixDisplayQrCode"
        },
        {
            "name": "promptpayDisplayQrCode",
            "baseName": "promptpay_display_qr_code",
            "type": "NextActionPromptpayDisplayQrCode"
        },
        {
            "name": "redirectToUrl",
            "baseName": "redirect_to_url",
            "type": "NextActionRedirectToUrl"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "useStripeSdk",
            "baseName": "use_stripe_sdk",
            "type": "object"
        },
        {
            "name": "verifyWithMicrodeposits",
            "baseName": "verify_with_microdeposits",
            "type": "NextActionVerifyWithMicrodeposits"
        },
        {
            "name": "wechatPayDisplayQrCode",
            "baseName": "wechat_pay_display_qr_code",
            "type": "NextActionWechatPayDisplayQrCode"
        },
        {
            "name": "wechatPayRedirectToAndroidApp",
            "baseName": "wechat_pay_redirect_to_android_app",
            "type": "NextActionWechatPayRedirectToAndroidApp"
        },
        {
            "name": "wechatPayRedirectToIosApp",
            "baseName": "wechat_pay_redirect_to_ios_app",
            "type": "NextActionWechatPayRedirectToIosApp"
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentIntentNextAction.attributeTypeMap;
    }
}

