/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripeRefund } from './stripeRefund';

/**
* A list of refunds that have been applied to the charge.
*/
export class StripeChargeRefunds {
    'object': StripeChargeRefunds.ObjectEnum;
    'data': Array<StripeRefund>;
    /**
    * True if this list has another page of items after this one that can be fetched.
    */
    'hasMore': boolean;
    /**
    * The URL where this list can be accessed.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeChargeRefunds.ObjectEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<StripeRefund>"
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StripeChargeRefunds.attributeTypeMap;
    }
}

export namespace StripeChargeRefunds {
    export enum ObjectEnum {
        LIST = <any> 'list'
    }
}
