/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StripeCoupon } from './stripeCoupon';
import { StripeDeletedDiscount } from './stripeDeletedDiscount';
import { StripeDiscount } from './stripeDiscount';
import { StripeDiscountCustomer } from './stripeDiscountCustomer';
import { StripeDiscountPromotionCode } from './stripeDiscountPromotionCode';

export class StripeInvoiceDiscountsInner {
    /**
    * The ID of the discount object. Discounts cannot be fetched by ID. Use `expand[]=discounts` in API calls to expand discount IDs in an array.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': StripeInvoiceDiscountsInner.ObjectEnum;
    /**
    * The Checkout session that this coupon is applied to, if it is applied to a particular session in payment mode. Will not be present for subscription mode.
    */
    'checkoutSession': string | null;
    'coupon': StripeCoupon;
    'customer': StripeDiscountCustomer | null;
    /**
    * Always true for a deleted object
    */
    'deleted': StripeInvoiceDiscountsInner.DeletedEnum;
    /**
    * If the coupon has a duration of `repeating`, the date that this discount will end. If the coupon has a duration of `once` or `forever`, this attribute will be null.
    */
    'end': number | null;
    /**
    * The invoice that the discount\'s coupon was applied to, if it was applied directly to a particular invoice.
    */
    'invoice': string | null;
    /**
    * The invoice item `id` (or invoice line item `id` for invoice line items of type=\'subscription\') that the discount\'s coupon was applied to, if it was applied directly to a particular invoice item or invoice line item.
    */
    'invoiceItem': string | null;
    'promotionCode': StripeDiscountPromotionCode | null;
    /**
    * Date that the coupon was applied.
    */
    'start': number;
    /**
    * The subscription that this coupon is applied to, if it is applied to a particular subscription.
    */
    'subscription': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "StripeInvoiceDiscountsInner.ObjectEnum"
        },
        {
            "name": "checkoutSession",
            "baseName": "checkout_session",
            "type": "string"
        },
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "StripeCoupon"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "StripeDiscountCustomer"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "StripeInvoiceDiscountsInner.DeletedEnum"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "string"
        },
        {
            "name": "invoiceItem",
            "baseName": "invoice_item",
            "type": "string"
        },
        {
            "name": "promotionCode",
            "baseName": "promotion_code",
            "type": "StripeDiscountPromotionCode"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StripeInvoiceDiscountsInner.attributeTypeMap;
    }
}

export namespace StripeInvoiceDiscountsInner {
    export enum ObjectEnum {
        DISCOUNT = <any> 'discount'
    }
    export enum DeletedEnum {
        TRUE = <any> true
    }
}
