/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionItemBillingThresholds {
    /**
    * Usage threshold that triggers the subscription to create an invoice
    */
    'usageGte': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "usageGte",
            "baseName": "usage_gte",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionItemBillingThresholds.attributeTypeMap;
    }
}

