/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PauseCollectionBehavior } from './pauseCollectionBehavior';

export class SubscriptionPauseCollection {
    'behavior': PauseCollectionBehavior;
    /**
    * The time after which the subscription will resume collecting payments.
    */
    'resumesAt': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "behavior",
            "baseName": "behavior",
            "type": "PauseCollectionBehavior"
        },
        {
            "name": "resumesAt",
            "baseName": "resumes_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPauseCollection.attributeTypeMap;
    }
}

