/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LocationSource } from './locationSource';

export class TaxLocation {
    /**
    * The customer\'s country as identified by Stripe Tax.
    */
    'country': string;
    'source': LocationSource;
    /**
    * The customer\'s state, county, province, or region as identified by Stripe Tax.
    */
    'state': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "LocationSource"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TaxLocation.attributeTypeMap;
    }
}

export namespace TaxLocation {
}
