/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BreakdownDiscount } from './breakdownDiscount';
import { BreakdownTax } from './breakdownTax';

export class TotalDetailsBreakdown {
    /**
    * The aggregated discounts.
    */
    'discounts': Array<BreakdownDiscount>;
    /**
    * The aggregated tax amounts by rate.
    */
    'taxes': Array<BreakdownTax>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Array<BreakdownDiscount>"
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "Array<BreakdownTax>"
        }    ];

    static getAttributeTypeMap() {
        return TotalDetailsBreakdown.attributeTypeMap;
    }
}

