/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FinancialConnectionsPermission } from './financialConnectionsPermission';

export class UsBankAccountFinancialConnections {
    /**
    * The list of permissions to request. The `payment_method` permission must be included.
    */
    'permissions'?: Array<FinancialConnectionsPermission>;
    /**
    * For webview integrations only. Upon completing OAuth login in the native browser, the user will be redirected to this URL to return to your app.
    */
    'returnUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<FinancialConnectionsPermission>"
        },
        {
            "name": "returnUrl",
            "baseName": "return_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UsBankAccountFinancialConnections.attributeTypeMap;
    }
}

