/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum WalletType {
    AMEX_EXPRESS_CHECKOUT = <any> 'amex_express_checkout',
    APPLE_PAY = <any> 'apple_pay',
    GOOGLE_PAY = <any> 'google_pay',
    MASTERPASS = <any> 'masterpass',
    SAMSUNG_PAY = <any> 'samsung_pay',
    VISA_CHECKOUT = <any> 'visa_checkout'
}
