/**
 * aha-nft-mgmt-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WalletMasterpassBillingAddress } from './walletMasterpassBillingAddress';
import { WalletMasterpassShippingAddress } from './walletMasterpassShippingAddress';

export class WalletVisaCheckout {
    'billingAddress': WalletMasterpassBillingAddress | null;
    /**
    * Owner\'s verified email. Values are verified or provided by the wallet directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'email': string | null;
    /**
    * Owner\'s verified full name. Values are verified or provided by the wallet directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'name': string | null;
    'shippingAddress': WalletMasterpassShippingAddress | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billing_address",
            "type": "WalletMasterpassBillingAddress"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "shippingAddress",
            "baseName": "shipping_address",
            "type": "WalletMasterpassShippingAddress"
        }    ];

    static getAttributeTypeMap() {
        return WalletVisaCheckout.attributeTypeMap;
    }
}

